add_library(Graphic SHARED)
target_sources(Graphic
        PRIVATE
        graphic/config.hpp
        graphic/Graphic.hpp
        graphic/Graphic.cpp
        graphic/TextureFormat.hpp
        render/Texture.hpp
        render/Texture.cpp
        graphic/Image.hpp
        graphic/Image.cpp
        graphic/ImageReader.hpp
        graphic/ImageLoader.hpp
        graphic/ImageLoader.cpp
        render/RenderElement.hpp
        render/RenderDeviceFactory.hpp
        render/Shader.hpp
        render/Shader.cpp
        render/IndexBufferObject.hpp
        render/IndexBufferObject.cpp
        render/RenderDevice.hpp
        render/VertexBufferObject.hpp
        render/VertexBufferObject.cpp
        render/VertexLayout.cpp
        render/VertexLayout.hpp
        render/VertexLayoutDescriptor.h
        render/private/IndexBufferObjectPrivate.hpp
        render/private/ShaderPrivate.hpp
        render/private/TexturePrivate.hpp
        render/private/VertexBufferPrivate.hpp
        render/private/VertexLayoutPrivate.hpp

        event/application/WindowCloseEvent.cpp
        event/application/WindowResizeEvent.cpp
        event/application/WindowCloseEvent.h
        event/application/WindowResizeEvent.h
        event/keyboard/KeyEvent.cpp
        event/keyboard/KeyPressedEvent.cpp
        event/keyboard/KeyTypedEvent.h
        event/keyboard/KeyPressedEvent.h
        event/keyboard/KeyEvent.h
        event/keyboard/KeyTypedEvent.cpp
        event/keyboard/KeyReleasedEvent.h
        event/keyboard/KeyReleasedEvent.cpp
        event/mouse/MouseButtonEvent.cpp
        event/mouse/MouseMovedEvent.h
        event/mouse/MouseButtonEvent.h
        event/mouse/MouseButtonPressedEvent.cpp
        event/mouse/MouseButtonPressedEvent.h
        event/mouse/MouseButtonReleasedEvent.h
        event/mouse/MouseButtonReleasedEvent.cpp
        event/mouse/MouseScrolledEvent.h
        event/mouse/MouseScrolledEvent.cpp
        event/mouse/MouseMovedEvent.cpp
        )
target_link_libraries(Graphic PUBLIC Core)
target_include_directories(Graphic PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>)
target_compile_definitions(Graphic PUBLIC BM_SHARED_GRAPHIC PRIVATE BM_BUILD_GRAPHIC)
configure_binary_output(Graphic)