find_package(benchmark QUIET)
if (NOT benchmark_FOUND)
    set(BENCHMARK_OUTPUT ${CMAKE_SOURCE_DIR} CACHE INTERNAL "Output directory of download")
    set(BENCHMARK_DIR benchmark-1.5.3 CACHE INTERNAL "SRC directory name of benchmark")
    set(BENCHMARK_PATH ${BENCHMARK_OUTPUT}/${BENCHMARK_DIR} CACHE INTERNAL "Full path name to benchmark directory")

    find_program(TAR_COMMAND tar)
    message(STATUS "tar found : ${TAR_COMMAND}")
    if(NOT IS_DIRECTORY ${BENCHMARK_PATH} OR NOT EXISTS ${BENCHMARK_PATH}/CMakefile.txt)
        message(STATUS "download google benchmark")
        file(DOWNLOAD https://github.com/google/benchmark/archive/refs/tags/v1.5.3.tar.gz ${BENCHMARK_OUTPUT}/v1.5.3.tar.gz)

        message(STATUS "extract benchmark dependency")
        execute_process(COMMAND ${TAR_COMMAND} -xf ${BENCHMARK_OUTPUT}/v1.5.3.tar.gz WORKING_DIRECTORY ${BENCHMARK_OUTPUT})
    endif()
    message(STATUS "use downloaded google benchmark")
    set(BENCHMARK_ENABLE_TESTING OFF)
    set(BENCHMARK_ENABLE_GTEST_TESTS OFF)

    add_subdirectory(${BENCHMARK_PATH})
endif ()